# Generated by Django 3.1.6 on 2021-08-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id_folder', models.AutoField(primary_key=True, serialize=False)),
                ('name_folder', models.CharField(max_length=80)),
                ('desc_folder', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=80)),
                ('user_password', models.CharField(max_length=80)),
                ('name_user', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('img_task', models.CharField(max_length=150)),
                ('desc_task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='sub_task',
            fields=[
                ('id_sub_task', models.AutoField(primary_key=True, serialize=False)),
                ('desc_sub_task', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.task')),
            ],
        ),
    ]
