# Generated by Django 3.1.6 on 2021-09-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210825_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.folder'),
        ),
    ]
