# Generated by Django 3.1.6 on 2021-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210909_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date_task',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_task',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
