# Generated by Django 3.1.6 on 2021-11-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211104_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_files',
            new_name='Task_file',
        ),
    ]
