# Generated by Django 3.1.6 on 2021-11-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20211104_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank='False', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.project'),
            preserve_default=False,
        ),
    ]
