# Generated by Django 3.1.6 on 2021-11-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20211105_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_file',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='user.task'),
        ),
    ]
