# Generated by Django 3.1.6 on 2021-11-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20211105_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_file',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user.task'),
        ),
    ]
